<div id="menu1"></div>
<? include("blocks/12-eff.php");?>
<? include("blocks/rek1.php");?>
<? include("blocks/where.php");?>
<div id="menu2"></div>
<? include("blocks/how.php");?>
<? include("blocks/razrab.php");?>
<? include("blocks/sertif.php");?>
<? include("blocks/srav-table.php");?>
<div id="menu3"></div>
<? include("blocks/otz.php");?>
<div id="menu4"></div>
<? include("blocks/why.php");?>
<? include("blocks/forma1.php");?>
<? include("blocks/skolko.php");?>
<? include("blocks/pribil.php");?>
<div id="menu5"></div>
<? include("blocks/forma2.php");?>
<? include("blocks/work.php");?>
<? include("blocks/contacts.php");?>