<? include("blocks/video.php");?>
<? include("blocks/choice.php");?>
<? include("blocks/opisanie.php");?>
<? include("blocks/podarok.php");?>
<? include("blocks/reasons.php");?>
<? include("blocks/box1.php");?>
<? include("blocks/box2.php");?>
<? include("blocks/otz.php");?>
<? include("blocks/script.php");?>