<? include("blocks/cifra.php");?>
<? include("blocks/zakaz_okon.php");?>
<? include("blocks/calc.php");?>
<? include("blocks/vibor.php");?>
<? include("blocks/work.php");?>
<? include("blocks/reasons.php");?>
<? include("blocks/otz.php");?>
<? include("blocks/box5.php");?>
<? include("blocks/map.php");?>
<? include("blocks/footer.php");?>